import { AlertCircle, BookOpen, CalendarDays, CheckCircle2, Clock3, FileText, Paperclip } from 'lucide-react';
import { formatAssignmentDate, getAssignmentDaysLabel, getAssignmentStatus, type Assignment } from '../../data/student-assignments';

interface AssignmentCardProps { assignment: Assignment; onView: () => void; }

export const AssignmentCard = ({ assignment, onView }: AssignmentCardProps) => {
    const status = getAssignmentStatus(assignment);
    const statusStyles = { 'Not Submitted': 'bg-slate-100 text-slate-600', Submitted: 'bg-indigo-50 text-indigo-700', Late: 'bg-amber-50 text-amber-700', Evaluated: 'bg-emerald-50 text-emerald-700', Overdue: 'bg-rose-50 text-rose-700' };
    const StatusIcon = status === 'Evaluated' || status === 'Submitted' ? CheckCircle2 : status === 'Overdue' ? AlertCircle : Clock3;

    return <article className="rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm shadow-slate-200/60"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><div className="rounded-lg bg-indigo-50 p-2 text-indigo-600"><BookOpen className="h-4 w-4" /></div><p className="text-xs font-bold uppercase tracking-[0.14em] text-indigo-600">{assignment.subjectCode}</p></div><h2 className="mt-3 text-lg font-extrabold text-slate-900">{assignment.title}</h2><p className="mt-1 text-sm font-semibold text-slate-600">{assignment.subjectName}</p></div><span className={`inline-flex shrink-0 items-center gap-1.5 rounded-full px-2.5 py-1.5 text-xs font-bold ${statusStyles[status]}`}><StatusIcon className="h-3.5 w-3.5" />{status}</span></div><p className="mt-3 flex items-center gap-2 text-xs font-semibold text-slate-500"><FileText className="h-4 w-4 text-slate-400" />{assignment.facultyName}</p><div className="mt-5 grid gap-3 border-t border-slate-100 pt-4 text-xs font-semibold text-slate-500 sm:grid-cols-2"><span className="flex items-center gap-2"><CalendarDays className="h-4 w-4 text-indigo-500" />Assigned {formatAssignmentDate(assignment.assignedDate)}</span><span className="flex items-center gap-2"><Clock3 className="h-4 w-4 text-indigo-500" />Due {formatAssignmentDate(assignment.dueDate)}</span></div>{status === 'Evaluated' && assignment.submission.marks !== null && <p className="mt-4 text-sm font-bold text-emerald-700">Marks: {assignment.submission.marks} / {assignment.maxMarks}</p>}{(status === 'Not Submitted' || status === 'Overdue') && <p className={`mt-4 text-sm font-bold ${status === 'Overdue' ? 'text-rose-700' : 'text-indigo-700'}`}>{getAssignmentDaysLabel(assignment)}</p>}<p className="mt-3 flex items-center gap-1.5 text-xs font-semibold text-slate-400"><Paperclip className="h-3.5 w-3.5" />{assignment.attachment.name}</p><button type="button" onClick={onView} className="mt-5 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white shadow-sm shadow-indigo-600/20 hover:bg-indigo-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:ring-offset-2">View Assignment</button></article>;
};